name: build visualization image

on:
  push:
    branches: [ "**" ]
    paths:
      - "**/Dockerfile*"
      - ".gitmodules"
  pull_request:
    branches: [ "**" ]
    paths:
      - "**/Dockerfile*"
      - ".gitmodules"

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
    runs-on: ${{matrix.os}}
    name: Build Docker container
    steps:
    - name: Check out the workshop repo
      uses: actions/checkout@v4
    - name: Extract the branch name
      id: branch
      run:
        echo "WORKSHOP_BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV
    - name: Filter the branch name to generate a tag for Docker
      id: tag
      run:
        echo "WORKSHOP_BRANCH_TAG=$(echo ${{env.WORKSHOP_BRANCH}} | sed -e 's/\//--/g')" >> $GITHUB_ENV
    - name: Output the branch name
      run:
        echo "Workshop Branch = ${{env.WORKSHOP_BRANCH}}"
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: yuanfornl
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: Get runner architecture
      run: |
        if [[ ${{matrix.os}} == "ubuntu-24.04-arm" ]]; then
          echo "ARCH=arm64" >> $GITHUB_ENV
        else
          echo "ARCH=amd64" >> $GITHUB_ENV
        fi
    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Docker/Dockerfile-vis
        tags: yuanfornl/ngee-modex-visualization:${{env.WORKSHOP_BRANCH_TAG}}-${{env.ARCH}}-latest

  fix-manifest:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: yuanfornl
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Extract the branch name
        id: branch
        run:
          echo "WORKSHOP_BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV
      - name: Filter the branch name to generate a tag for Docker
        id: tag
        run:
          echo "WORKSHOP_BRANCH_TAG=$(echo ${{env.WORKSHOP_BRANCH}} | sed -e 's/\//--/g')" >> $GITHUB_ENV
      - name: Pull images (remove with artifacts??)
        run: |
          docker pull yuanfornl/ngee-modex-visualization:${{env.WORKSHOP_BRANCH_TAG}}-arm64-latest
          docker pull yuanfornl/ngee-modex-visualization:${{env.WORKSHOP_BRANCH_TAG}}-amd64-latest
      - name: Edit manifest
        run: |
          docker manifest create yuanfornl/ngee-modex-visualization:${{env.WORKSHOP_BRANCH_TAG}}-latest \
            --amend yuanfornl/ngee-modex-visualization:${{env.WORKSHOP_BRANCH_TAG}}-arm64-latest \
            --amend yuanfornl/ngee-modex-visualization:${{env.WORKSHOP_BRANCH_TAG}}-amd64-latest
          docker manifest push yuanfornl/ngee-modex-visualization:${{env.WORKSHOP_BRANCH_TAG}}-latest
